slam_toolbox:
  ros__parameters:
    use_sim_time: true

    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.2
    transform_publish_period: 0.02
    map_update_interval: 2.0

    # 滑移转向里程计漂移较大，放宽匹配搜索范围
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    scan_buffer_size: 10

    do_loop_closing: true
    loop_search_maximum_distance: 4.0
